### ISSUE TITLE
Validate NCBI imports

### ISSUE THREAD

**Issue by pbuttigieg** [EnvironmentOntology/biorealm#2]
Hi @thearyung 

In 3a9b1b5ff7cc0a4d6d243675cef06cea815bf51b, I've added the NCBITaxon import to the imports/ directory and in f05983b5f0e1acaa2b05fd8351ffd38391d3fdd2 I updated the Protégé catalogue file to import it into the editors version. Please validate that you see the classes you added to the ncbitaxon_terms.txt file.

PS: The Travis CI build checks are now enabled since 352489ff90779d0227b9c4accf53f43cc22dbea6

**Comment by thearyung** [comment]
Hi @pbuttigieg 
thanks a lot! It works!
